name: First Action

on: 
  workflow_dispatch:
  
jobs:
  hello:
    name: Say Hello
    runs-on: ubuntu-latest # cheapest option if you scale up too far; this one is good for most cases
    steps:
      - name: Hello world
      - run: echo "Hello world"
